###User sign up
POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name":"Vignesh",
    "company":"Vignesh Tech Limited",
    "address":"Chennai,Tamil Nadu",
    "phone":"8056186732",
    "email":"vicky241097@gmail.com",
    "password":"Arsenal@2021"
}

###User sign in
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
 "email":"vicky241097@gmail.com",
 "password":"Arsenal@2021"
}
###Get a user profile endpoint
GET http://localhost:3001/v1/user
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZpY2t5MjQxMDk3QGdtYWlsLmNvbSIsImlhdCI6MTY2Mjc0ODI0NywiZXhwIjoxNjYyNzQ4MzA3fQ.BY9kMaCZ1sTbX1DnE1fG_0VuRdc5xObihqoAWCFTiVw
Content-Type: application/json

{
 "email":"vicky241097@gmail.com",
 "password":"Arsenal@2021"
}

###Token Routers
###Get refreshed token
GET http://localhost:3001/v1/tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZpY2t5MjQxMDk3QGdtYWlsLmNvbSIsImlhdCI6MTY2MjY0NzA4MiwiZXhwIjoxNjY1MjM5MDgyfQ.LLsW_KFugsjjQMHeVx2E4zjQ26mIJcT4_WxgegpL0TU  
